force-app/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <label>Feedback Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Feedback__c/fields/At_Risk__c.field-meta.xml
<CustomField>
    <fullName>At_Risk__c</fullName>
    <defaultValue>false</defaultValue>
    <label>At Risk</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Off Track</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Completion__c.field-meta.xml
<CustomField>
    <fullName>Completion__c</fullName>
    <label>Completion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Next_Week_s_plan__c.field-meta.xml
<CustomField>
    <fullName>Next_Week_s_plan__c</fullName>
    <label>Next Week&apos;s plan</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Notes_for_Leadership__c.field-meta.xml
<CustomField>
    <fullName>Notes_for_Leadership__c</fullName>
    <label>Notes for Leadership</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Planned_Activities_Deliverables__c.field-meta.xml
<CustomField>
    <fullName>Planned_Activities_Deliverables__c</fullName>
    <label>Planned Activities &amp; Deliverables</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Progress_Summary_or_Key_Accomplishments__c.field-meta.xml
<CustomField>
    <fullName>Progress_Summary_or_Key_Accomplishments__c</fullName>
    <label>Progress Summary or Key Accomplishments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Project_Phase__c.field-meta.xml
<CustomField>
    <fullName>Project_Phase__c</fullName>
    <label>Project Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Execution</fullName>
            </value>
            <value>
                <fullName>Initiation</fullName>
            </value>
            <value>
                <fullName>Closure</fullName>
            </value>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Reporting_Week__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Week__c</fullName>
    <label>Reporting Week</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Risk_Blockers__c.field-meta.xml
<CustomField>
    <fullName>Risk_Blockers__c</fullName>
    <label>Risk/Blockers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Feedback__c/fields/Team_Morale__c.field-meta.xml
<CustomField>
    <fullName>Team_Morale__c</fullName>
    <label>Team Morale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bad</fullName>
            </value>
            <value>
                <fullName>Could be better</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Great</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(
  AND(
    NOT(ISBLANK(Start_Date__c)),
    NOT(ISBLANK(End_Date__c)),
    TODAY() &gt;= Start_Date__c,
    TODAY() &lt;= End_Date__c
  ),
  &quot;Active&quot;,
  &quot;Inactive&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/weeklyStatusFormController.cls
public with sharing class weeklyStatusFormController {
    
    @AuraEnabled(cacheable=true)
    public static List<Project__c> getProjects() {
        return [SELECT Id, Name, Start_Date__c FROM Project__c ORDER BY Name ASC];
    }
    
    @AuraEnabled
    public static Id saveFeedback(Feedback__c feedback) {
        
        if (feedback.Id == null) {
            insert feedback;
        } else {
            update feedback;
        }
        
        return feedback.Id;
    }
    @AuraEnabled
    public static Feedback__c getLatestDraft(Id projectId) {
        
        List<Feedback__c> drafts = [
        SELECT Id, Name, Project__c,
            Reporting_Week__c,
            At_Risk__c,
            Blocked__c,
            Completion__c,
            Project_Phase__c,
            Progress_Summary_or_Key_Accomplishments__c,
            Next_Week_s_plan__c,
            Planned_Activities_Deliverables__c,
            Risk_Blockers__c,
            Notes_for_Leadership__c,
            Team_Morale__c
        FROM Feedback__c
        WHERE  CreatedById = :UserInfo.getUserId()
        AND Status__c = 'Draft'
        ORDER BY CreatedDate DESC
        LIMIT 1
    ];
        
        if (drafts.isEmpty()) {
            return null;
        }
        
        return drafts[0];
    }
    @AuraEnabled(cacheable=false)
    public static List<ContentDocumentLink> getFeedbackFiles(Id recordId) {
        
        return [
        SELECT ContentDocumentId,
               ContentDocument.Title,
               ContentDocument.FileType,
               ContentDocument.FileExtension,
               ContentDocument.LatestPublishedVersionId
        FROM ContentDocumentLink
        WHERE LinkedEntityId = :recordId
        ORDER BY ContentDocument.CreatedDate DESC
    ];
    }
    @AuraEnabled
    public static void deleteFile(Id contentDocumentId, Id feedbackId) {
        
        ContentDocumentLink[] link = [
        SELECT Id
        FROM ContentDocumentLink
        WHERE ContentDocumentId = :contentDocumentId
        AND LinkedEntityId = :feedbackId
    ];
        if(link.isEmpty()) return;
        delete link;
    }
}